FROM node:alpine

RUN apk --no-cache upgrade && apk add yarn

ENV UPLOAD_PATH=/var/lib/gallery/photos
ENV SERVER_PORT=5200

WORKDIR /opt/gallery
COPY ./package.json package.json
COPY ./yarn.lock yarn.lock
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build:server

RUN mkdir -p /var/lib/gallery/photos/marked \
  &&  mkdir -p /var/lib/gallery/photos/thumb

EXPOSE 5200

ENTRYPOINT ["node", "build_server"]
